-- 0. Ensure user_ratings has metadata columns
alter table user_ratings add column if not exists name text;
alter table user_ratings add column if not exists image_url text;

-- 1. Create legacy_users table
create table if not exists legacy_users (
  username text primary key,
  access_code text not null
);

-- 2. Create legacy_ratings table
create table if not exists legacy_ratings (
  id bigint generated by default as identity primary key,
  game_id text not null,
  username text references legacy_users(username) on delete cascade,
  rating int not null,
  name text,
  image_url text
);

-- Ensure columns exist if table already existed
alter table legacy_ratings add column if not exists name text;
alter table legacy_ratings add column if not exists image_url text;

-- 2.1 Create profiles table to track user state (e.g. claimed_legacy)
create table if not exists profiles (
  id uuid references auth.users primary key,
  claimed_legacy boolean default false
);
alter table profiles enable row level security;

drop policy if exists "Users can view own profile" on profiles;
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);

drop policy if exists "Users can update own profile" on profiles;
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on profiles;
create policy "Users can insert own profile" on profiles for insert with check (auth.uid() = id);

-- 3. Enable RLS
alter table legacy_users enable row level security;
alter table legacy_ratings enable row level security;

-- 4. Create policies (allow read for everyone for now, or restrict)
drop policy if exists "Enable read access for all users" on legacy_users;
create policy "Enable read access for all users" on legacy_users for select using (true);

drop policy if exists "Enable read access for all users" on legacy_ratings;
create policy "Enable read access for all users" on legacy_ratings for select using (true);

-- 5. Create view for average ratings (combines user_ratings and legacy_ratings)
create or replace view game_averages as
select 
  game_id, 
  avg(rating)::numeric(10,2) as average_rating,
  count(*) as rating_count
from (
  select game_id, rating from user_ratings
  union all
  select game_id, rating from legacy_ratings
) as all_ratings
group by game_id;

-- 6. Function to claim ratings
create or replace function claim_legacy_ratings(p_access_code text)
returns json as $$
declare
  v_username text;
  v_count int;
begin
  -- Find user by access code
  select username into v_username from legacy_users where access_code = p_access_code;
  
  if v_username is null then
    return json_build_object('success', false, 'message', 'Código inválido');
  end if;

  -- Insert into user_ratings (updating metadata if exists)
  -- We use DISTINCT ON (game_id) to avoid "ON CONFLICT DO UPDATE command cannot affect row a second time"
  -- if legacy_ratings has duplicates for the same game.
  with source_ratings as (
    select distinct on (game_id) game_id, rating, name, image_url
    from legacy_ratings
    where username = v_username
    order by game_id, id desc -- Pick the latest one (highest ID) if duplicates exist
  ),
  inserted as (
    insert into user_ratings (user_id, game_id, rating, name, image_url, created_at)
    select auth.uid(), game_id, rating, name, image_url, now()
    from source_ratings
    on conflict (user_id, game_id) do update
    set 
      name = excluded.name,
      image_url = excluded.image_url
    returning 1
  )
  select count(*) into v_count from inserted;

  -- Delete from legacy_ratings
  delete from legacy_ratings where username = v_username;
  
  -- Delete from legacy_users
  delete from legacy_users where username = v_username;

  -- Mark as claimed in profiles
  insert into profiles (id, claimed_legacy) values (auth.uid(), true)
  on conflict (id) do update set claimed_legacy = true;
  
  return json_build_object('success', true, 'message', 'Histórico resgatado com sucesso!', 'count', v_count);
end;
$$ language plpgsql security definer;

-- 7. Function to reset account (DEBUG ONLY)
create or replace function reset_account()
returns void as $$
begin
  delete from user_ratings where user_id = auth.uid();
  delete from user_games where user_id = auth.uid();
  update profiles set claimed_legacy = false where id = auth.uid();
end;
$$ language plpgsql security definer;
